// <auto-generated />
using System;
using MarcaAi.Domain.Enums;
using MarcaAi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarcaAi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260725145542_AddFinancialSplit")]
    partial class AddFinancialSplit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "BookingStatus", new[] { "CANCELLED", "CONFIRMED", "NO_SHOW", "PENDING", "RESCHEDULED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "CanceledBy", new[] { "GUEST", "OWNER", "SYSTEM" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "EventTypeColor", new[] { "AMBER", "CYAN", "EMERALD", "FUCHSIA", "ORANGE", "ROSE", "SLATE", "TEAL", "VIOLET" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "ExceptionType", new[] { "BLOCKED", "OVERRIDE", "VACATION" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "LocationType", new[] { "CUSTOM", "GOOGLE_MEET", "IN_PERSON", "PHONE", "TEAMS", "ZOOM" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "PaymentProvider", new[] { "MERCADO_PAGO", "STRIPE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "PaymentStatus", new[] { "FAILED", "PAID", "PARTIALLY_REFUNDED", "PENDING", "REFUNDED", "UNPAID" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "PayoutAccountStatus", new[] { "ACTIVE", "DISABLED", "PENDING", "RESTRICTED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "PayoutOwnerType", new[] { "TEAM", "USER" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "QuestionType", new[] { "CHECKBOX", "PHONE", "SELECT", "TEXT", "TEXTAREA" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "TeamRole", new[] { "ADMIN", "MEMBER", "OWNER" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "Theme", new[] { "DARK", "LIGHT", "SYSTEM" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarcaAi.Domain.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<int?>("ExpiresAt")
                        .HasColumnType("integer")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdToken")
                        .HasColumnType("text")
                        .HasColumnName("id_token");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("providerAccountId");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("SessionState")
                        .HasColumnType("text")
                        .HasColumnName("session_state");

                    b.Property<string>("TokenType")
                        .HasColumnType("text")
                        .HasColumnName("token_type");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderAccountId")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.Booking", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text")
                        .HasColumnName("cancelReason");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canceledAt");

                    b.Property<CanceledBy?>("CanceledBy")
                        .HasColumnType("\"CanceledBy\"")
                        .HasColumnName("canceledBy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("endTime");

                    b.Property<string>("EventTypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eventTypeId");

                    b.Property<int?>("GatewayFeeCents")
                        .HasColumnType("integer")
                        .HasColumnName("gatewayFeeCents");

                    b.Property<string>("GuestEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guestEmail");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guestName");

                    b.Property<string>("GuestNotes")
                        .HasColumnType("text")
                        .HasColumnName("guestNotes");

                    b.Property<string>("GuestPhone")
                        .HasColumnType("text")
                        .HasColumnName("guestPhone");

                    b.Property<string>("GuestTimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guestTimeZone");

                    b.Property<string>("MeetingId")
                        .HasColumnType("text")
                        .HasColumnName("meetingId");

                    b.Property<string>("MeetingUrl")
                        .HasColumnType("text")
                        .HasColumnName("meetingUrl");

                    b.Property<int?>("NetToProviderCents")
                        .HasColumnType("integer")
                        .HasColumnName("netToProviderCents");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paidAt");

                    b.Property<PaymentProvider?>("PaymentProvider")
                        .HasColumnType("\"PaymentProvider\"")
                        .HasColumnName("paymentProvider");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text")
                        .HasColumnName("paymentReference");

                    b.Property<PaymentStatus>("PaymentStatus")
                        .HasColumnType("\"PaymentStatus\"")
                        .HasColumnName("paymentStatus");

                    b.Property<string>("PayoutAccountId")
                        .HasColumnType("text")
                        .HasColumnName("payoutAccountId");

                    b.Property<int?>("PlatformFeeCents")
                        .HasColumnType("integer")
                        .HasColumnName("platformFeeCents");

                    b.Property<int?>("PriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("priceCents");

                    b.Property<string>("ProviderPaymentId")
                        .HasColumnType("text")
                        .HasColumnName("providerPaymentId");

                    b.Property<string>("RecurringEventId")
                        .HasColumnType("text")
                        .HasColumnName("recurringEventId");

                    b.Property<int?>("RecurringIndex")
                        .HasColumnType("integer")
                        .HasColumnName("recurringIndex");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refundedAt");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("boolean")
                        .HasColumnName("reminderSent");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("startTime");

                    b.Property<BookingStatus>("Status")
                        .HasColumnType("\"BookingStatus\"")
                        .HasColumnName("status");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("uid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("GuestEmail");

                    b.HasIndex("PayoutAccountId");

                    b.HasIndex("ProviderPaymentId");

                    b.HasIndex("StartTime");

                    b.HasIndex("Status");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "StartTime", "EndTime", "Status");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.BookingResponse", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bookingId");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("questionId");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("booking_responses", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.EventType", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AfterEventBuffer")
                        .HasColumnType("integer")
                        .HasColumnName("afterEventBuffer");

                    b.Property<int>("BeforeEventBuffer")
                        .HasColumnType("integer")
                        .HasColumnName("beforeEventBuffer");

                    b.Property<int?>("BookingLimitDays")
                        .HasColumnType("integer")
                        .HasColumnName("bookingLimitDays");

                    b.Property<EventTypeColor>("Color")
                        .HasColumnType("\"EventTypeColor\"")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("isActive");

                    b.Property<LocationType>("LocationType")
                        .HasColumnType("\"LocationType\"")
                        .HasColumnName("locationType");

                    b.Property<string>("LocationValue")
                        .HasColumnType("text")
                        .HasColumnName("locationValue");

                    b.Property<int?>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<bool>("RequiresConfirm")
                        .HasColumnType("boolean")
                        .HasColumnName("requiresConfirm");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("TeamId")
                        .HasColumnType("text")
                        .HasColumnName("teamId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("Slug");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Slug")
                        .IsUnique();

                    b.ToTable("event_types", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.EventTypeQuestion", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("EventTypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eventTypeId");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Placeholder")
                        .HasColumnType("text")
                        .HasColumnName("placeholder");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<QuestionType>("Type")
                        .HasColumnType("\"QuestionType\"")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeId");

                    b.ToTable("event_type_questions", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.PayoutAccount", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("AbsorbGatewayCost")
                        .HasColumnType("boolean")
                        .HasColumnName("absorbGatewayCost");

                    b.Property<bool>("ChargesEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("chargesEnabled");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("externalAccountId");

                    b.Property<int?>("FeeFixedCents")
                        .HasColumnType("integer")
                        .HasColumnName("feeFixedCents");

                    b.Property<int?>("FeePercentBps")
                        .HasColumnType("integer")
                        .HasColumnName("feePercentBps");

                    b.Property<string>("OnboardingUrl")
                        .HasColumnType("text")
                        .HasColumnName("onboardingUrl");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ownerId");

                    b.Property<PayoutOwnerType>("OwnerType")
                        .HasColumnType("\"PayoutOwnerType\"")
                        .HasColumnName("ownerType");

                    b.Property<bool>("PayoutsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("payoutsEnabled");

                    b.Property<PaymentProvider>("Provider")
                        .HasColumnType("\"PaymentProvider\"")
                        .HasColumnName("provider");

                    b.Property<PayoutAccountStatus>("Status")
                        .HasColumnType("\"PayoutAccountStatus\"")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("OwnerType", "OwnerId");

                    b.HasIndex("Provider", "ExternalAccountId");

                    b.HasIndex("OwnerType", "OwnerId", "Provider")
                        .IsUnique();

                    b.ToTable("payout_accounts", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.Schedule", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("isDefault");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timeZone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.ScheduleAvailability", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("dayOfWeek");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endTime");

                    b.Property<string>("ScheduleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scheduleId");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("startTime");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.ToTable("schedule_availabilities", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.ScheduleException", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("EndTime")
                        .HasColumnType("text")
                        .HasColumnName("endTime");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("ScheduleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scheduleId");

                    b.Property<string>("StartTime")
                        .HasColumnType("text")
                        .HasColumnName("startTime");

                    b.Property<ExceptionType>("Type")
                        .HasColumnType("\"ExceptionType\"")
                        .HasColumnName("type");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("UserId");

                    b.ToTable("schedule_exceptions", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.Session", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sessionToken");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<int?>("DefaultFeeBps")
                        .HasColumnType("integer")
                        .HasColumnName("defaultFeeBps");

                    b.Property<string>("PlanCode")
                        .HasColumnType("text")
                        .HasColumnName("planCode");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StripeCurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stripeCurrentPeriodEnd");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stripeCustomerId");

                    b.Property<string>("StripePriceId")
                        .HasColumnType("text")
                        .HasColumnName("stripePriceId");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text")
                        .HasColumnName("stripeSubscriptionId");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("teamId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("StripeCustomerId")
                        .IsUnique();

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique();

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.Team", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BrandColor")
                        .HasColumnType("text")
                        .HasColumnName("brandColor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<Theme>("Theme")
                        .HasColumnType("\"Theme\"")
                        .HasColumnName("theme");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.TeamMember", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<TeamRole>("Role")
                        .HasColumnType("\"TeamRole\"")
                        .HasColumnName("role");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("teamId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.HasIndex("TeamId", "UserId")
                        .IsUnique();

                    b.ToTable("team_members", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("BrandColor")
                        .HasColumnType("text")
                        .HasColumnName("brandColor");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emailVerified");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("Onboarded")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarded");

                    b.Property<string>("RecurringEventId")
                        .HasColumnType("text")
                        .HasColumnName("recurringEventId");

                    b.Property<int?>("RecurringIndex")
                        .HasColumnType("integer")
                        .HasColumnName("recurringIndex");

                    b.Property<Theme>("Theme")
                        .HasColumnType("\"Theme\"")
                        .HasColumnName("theme");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timeZone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.VerificationToken", b =>
                {
                    b.Property<string>("Identifier")
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<string>("Token")
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.HasKey("Identifier", "Token");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("verification_tokens", (string)null);
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.Account", b =>
                {
                    b.HasOne("MarcaAi.Domain.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.Booking", b =>
                {
                    b.HasOne("MarcaAi.Domain.Entities.EventType", "EventType")
                        .WithMany("Bookings")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarcaAi.Domain.Entities.User", "Owner")
                        .WithMany("BookingsAsOwner")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.BookingResponse", b =>
                {
                    b.HasOne("MarcaAi.Domain.Entities.Booking", "Booking")
                        .WithMany("Responses")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.EventType", b =>
                {
                    b.HasOne("MarcaAi.Domain.Entities.Team", "Team")
                        .WithMany("EventTypes")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MarcaAi.Domain.Entities.User", "User")
                        .WithMany("EventTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.EventTypeQuestion", b =>
                {
                    b.HasOne("MarcaAi.Domain.Entities.EventType", "EventType")
                        .WithMany("Questions")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("MarcaAi.Domain.Entities.User", "User")
                        .WithMany("Schedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.ScheduleAvailability", b =>
                {
                    b.HasOne("MarcaAi.Domain.Entities.Schedule", "Schedule")
                        .WithMany("Availabilities")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.ScheduleException", b =>
                {
                    b.HasOne("MarcaAi.Domain.Entities.Schedule", "Schedule")
                        .WithMany("Exceptions")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarcaAi.Domain.Entities.User", "User")
                        .WithMany("ScheduleExceptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.Session", b =>
                {
                    b.HasOne("MarcaAi.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("MarcaAi.Domain.Entities.Team", "Team")
                        .WithOne("Subscription")
                        .HasForeignKey("MarcaAi.Domain.Entities.Subscription", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("MarcaAi.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarcaAi.Domain.Entities.User", "User")
                        .WithMany("TeamMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.EventType", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.Schedule", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("Exceptions");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.Team", b =>
                {
                    b.Navigation("EventTypes");

                    b.Navigation("Members");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("MarcaAi.Domain.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("BookingsAsOwner");

                    b.Navigation("EventTypes");

                    b.Navigation("ScheduleExceptions");

                    b.Navigation("Schedules");

                    b.Navigation("Sessions");

                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
